<!-- Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ -->
<script setup>
import {onMounted,reactive,ref} from 'vue';import {request} from '../api'
const rows=ref([]),dashboard=ref(null),error=ref('')
const form=reactive({runNo:'COMM-'+Date.now(),planNo:'PLAN-2026-H2',beneficiary:'销售顾问A',eligibleRevenue:800000,baseRate:3,acceleratorThreshold:500000,acceleratorRate:5,capAmount:60000,disputedItems:0,planApproved:true,dataLocked:true,complianceChecked:true})
async function load(){try{[rows.value,dashboard.value]=await Promise.all([request('/api/commission/runs'),request('/api/commission/runs/dashboard')])}catch(e){error.value=e.message}}
async function create(){try{await request('/api/commission/runs',{method:'POST',body:JSON.stringify(form)});form.runNo='COMM-'+Date.now();await load()}catch(e){error.value=e.message}}
async function act(i,a){if(!confirm('确认'+a+' '+i.runNo+'？'))return;try{if(a==='计算')await request(`/api/commission/runs/${i.id}/calculate`,{method:'POST'});if(a==='提交复核')await request(`/api/commission/runs/${i.id}/submit`,{method:'POST'});if(a==='批准')await request(`/api/admin/commission/runs/${i.id}/approve?remark=${encodeURIComponent('财务与人力复核通过')}`,{method:'POST'});if(a==='发放')await request(`/api/commission/runs/${i.id}/payout?paymentReference=${encodeURIComponent('PAY-'+i.runNo)}`,{method:'POST'});if(a==='追索')await request(`/api/commission/runs/${i.id}/clawback`,{method:'POST',body:JSON.stringify({amount:Math.min(1000,i.calculatedAmount-i.clawbackAmount),reason:'退单触发佣金追索'})});await load()}catch(e){error.value=e.message}}
const money=v=>new Intl.NumberFormat('zh-CN',{style:'currency',currency:'CNY'}).format(v||0)
onMounted(load)
</script>
<template><section class="head"><div><span>INCENTIVE OPERATIONS</span><h3>佣金计算与发放工作台</h3><p>阶梯费率、加速区间、方案封顶、争议与合规门禁、复核发放以及退款追索。</p></div><b>可解释计算</b></section><p v-if="error" class="error" @click="error=''">{{error}} ×</p>
<section v-if="dashboard" class="metrics"><article><span>计算批次</span><b>{{dashboard.total}}</b></article><article><span>待复核</span><b>{{dashboard.pendingReview}}</b></article><article><span>已发放</span><b>{{dashboard.paid}}</b></article><article><span>累计追索</span><b>{{money(dashboard.clawbackAmount)}}</b></article></section>
<form class="card form" @submit.prevent="create"><label>运行批次<input v-model="form.runNo" required></label><label>激励方案<input v-model="form.planNo" required></label><label class="wide">受益人<input v-model="form.beneficiary" required></label><label>有效业绩<input v-model.number="form.eligibleRevenue" type="number" min="0"></label><label>基础费率 %<input v-model.number="form.baseRate" type="number" min="0" step=".01"></label><label>加速阈值<input v-model.number="form.acceleratorThreshold" type="number" min="0"></label><label>加速费率 %<input v-model.number="form.acceleratorRate" type="number" min="0" step=".01"></label><label>封顶金额<input v-model.number="form.capAmount" type="number" min="1"></label><label>争议数量<input v-model.number="form.disputedItems" type="number" min="0"></label><label class="check"><input v-model="form.planApproved" type="checkbox">方案已审批</label><label class="check"><input v-model="form.dataLocked" type="checkbox">数据已锁定</label><label class="check"><input v-model="form.complianceChecked" type="checkbox">合规已检查</label><button>创建计算批次</button></form>
<section class="card table"><table><thead><tr><th>批次 / 受益人</th><th>业绩与费率</th><th>佣金</th><th>控制门禁</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="i in rows"><td><b>{{i.runNo}}</b><small>{{i.planNo}} · {{i.beneficiary}}</small></td><td>{{money(i.eligibleRevenue)}}<small>{{i.baseRate}}% / 加速 {{i.acceleratorRate}}%</small></td><td>{{money(i.calculatedAmount)}}<small>封顶 {{money(i.capAmount)}} · 追索 {{money(i.clawbackAmount)}}</small></td><td>争议 {{i.disputedItems}}<small>方案 {{i.planApproved?'✓':'×'}} · 锁定 {{i.dataLocked?'✓':'×'}} · 合规 {{i.complianceChecked?'✓':'×'}}</small></td><td>{{i.state}}</td><td><button v-if="i.state==='DRAFT'" class="text" @click="act(i,'计算')">计算</button><button v-if="i.state==='CALCULATED'" class="text" @click="act(i,'提交复核')">提交</button><button v-if="i.state==='PENDING_REVIEW'" class="text" @click="act(i,'批准')">批准</button><button v-if="i.state==='APPROVED'" class="text" @click="act(i,'发放')">发放</button><button v-if="['PAID','PARTIAL_CLAWBACK'].includes(i.state)" class="text danger" @click="act(i,'追索')">追索</button></td></tr></tbody></table></section></template>
<style scoped>.head{display:flex;justify-content:space-between;align-items:end;background:#fff;border:1px solid #dce2df;padding:24px 28px;margin-bottom:16px}.head span{font-size:11px;letter-spacing:.16em;color:#b47c2f}.head h3{font-size:24px;margin:5px 0}.head p{margin:0;color:#68777c}.head>b{color:#235a74}.metrics{margin-bottom:16px}.card{background:#fff;border:1px solid #dce2df;padding:20px;margin-bottom:16px}.form{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.form label{display:grid;gap:5px;font-size:12px;color:#68777c}.form input{border:1px solid #ccd6d2;padding:9px}.form .wide{grid-column:span 2}.check{display:flex!important;align-items:center;gap:7px}.check input{width:17px}.form button{border:0;background:#235a74;color:#fff;font-weight:700}.table{padding:0;overflow:auto}.table table{min-width:920px}td small{display:block;color:#68777c}.text{border:0;background:transparent;color:#235a74;padding:4px}.danger,.error{color:#a03f38}@media(max-width:900px){.form{grid-template-columns:1fr}.form .wide{grid-column:auto}}</style>
